-- Federico Mollica

DROP DATABASE IF EXISTS esercizio_db;
CREATE DATABASE IF NOT EXISTS esercizio_db;

USE esercizio_db;

CREATE TABLE IF NOT EXISTS ruolo (
	ID_G INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    TIPOLOGIA ENUM('Admin', 'Utente', 'Docente') NOT NULL
);

CREATE TABLE IF NOT EXISTS utente (
	ID_U INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    Nome VARCHAR(255) NOT NULL,
    Cognome VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS categoria (
	ID_CA INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    Nome_Categoria ENUM('FrontEnd', 'BackEnd', 'FullStack', 'Cybersecurity') NOT NULL
);

CREATE TABLE IF NOT EXISTS corso (
	ID_C INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    Descrizione_breve VARCHAR(255) NOT NULL,
    Descrizione_completa TEXT NOT NULL,
	durata INT NOT NULL,
    FK_CA INT NOT NULL,
    FOREIGN KEY (FK_CA) REFERENCES categoria (ID_CA)
);

CREATE TABLE IF NOT EXISTS utente_ruolo (
	FK_R INT NOT NULL,
    FK_U INT NOT NULL,
    PRIMARY KEY (FK_R, FK_U),
    FOREIGN KEY (FK_R) REFERENCES ruolo (ID_G),
    FOREIGN KEY (FK_U) REFERENCES utente (ID_U)
);

CREATE TABLE IF NOT EXISTS utenti_corsi (
	FK_UC INT NOT NULL,
    FK_CU INT NOT NULL,
    PRIMARY KEY (FK_UC, FK_CU),
    FOREIGN KEY (FK_UC) REFERENCES utente (ID_U),
    FOREIGN KEY (FK_CU) REFERENCES corso (ID_C)
);